# Generated by Django 5.0.6 on 2026-07-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='license_photo',
            field=models.FileField(blank=True, null=True, upload_to='drivers/licenses/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='drivers/photos/'),
        ),
    ]
