# Generated by Django 5.0.6 on 2026-07-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driverprofile_license_photo_driverprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='last_heading',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='last_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='last_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
