# Generated by Django 5.0.6 on 2026-07-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driverprofile_last_heading_driverprofile_last_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='id_card_photo',
            field=models.FileField(blank=True, null=True, upload_to='drivers/id_cards/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/'),
        ),
    ]
