# Generated by Django 5.0.6 on 2026-07-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_topupintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='topupintent',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
