# Generated by Django 5.0.6 on 2026-07-01 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=160)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='children/')),
                ('note_for_driver', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.parentprofile')),
            ],
            options={
                'db_table': 'children',
                'ordering': ['full_name'],
            },
        ),
    ]
