# Generated by Django 5.0.6 on 2026-07-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='grade',
            field=models.CharField(blank=True, max_length=20, verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='child',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
