# Generated by Django 5.0.6 on 2026-07-01 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='mock', max_length=20)),
                ('provider_ref', models.CharField(blank=True, db_index=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KZT', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('refunded', 'Возврат')], default='pending', max_length=12)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.parentprofile')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='trips.trip')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
