# Generated by Django 5.0.6 on 2026-07-01 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('children', '0001_initial'),
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_text', models.CharField(max_length=255)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('dropoff_text', models.CharField(max_length=255)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
                ('weekdays', models.JSONField(default=list)),
                ('pickup_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_plans', to='accounts.parentprofile')),
                ('tariff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.tariff')),
            ],
            options={
                'db_table': 'recurring_trip_plans',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_text', models.CharField(max_length=255)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('dropoff_text', models.CharField(max_length=255)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
                ('scheduled_at', models.DateTimeField()),
                ('route_distance_m', models.PositiveIntegerField(default=0)),
                ('route_duration_s', models.PositiveIntegerField(default=0)),
                ('route_polyline', models.JSONField(blank=True, default=list)),
                ('price_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_currency', models.CharField(default='KZT', max_length=8)),
                ('status', models.CharField(choices=[('created', 'Создан'), ('waiting_payment', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('driver_assigned', 'Водитель назначен'), ('driver_on_way', 'Водитель выехал'), ('driver_arrived', 'Водитель прибыл'), ('child_picked_up', 'Ребёнок забран'), ('in_progress', 'В пути'), ('child_delivered', 'Ребёнок доставлен'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='created', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Не оплачен'), ('pending', 'В обработке'), ('paid', 'Оплачен'), ('refunded', 'Возврат'), ('failed', 'Ошибка')], default='unpaid', max_length=12)),
                ('driver_earning_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='children.child')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='drivers.driverprofile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='accounts.parentprofile')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='trips.recurringtripplan')),
                ('tariff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.tariff')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.vehicle')),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='TripLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driverprofile')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='trips.trip')),
            ],
            options={
                'db_table': 'trip_locations',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='TripStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('event', models.CharField(blank=True, max_length=40)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='trips.trip')),
            ],
            options={
                'db_table': 'trip_status_history',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='trips_status_b30e85_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver', 'status'], name='trips_driver__f38efc_idx'),
        ),
        migrations.AddIndex(
            model_name='triplocation',
            index=models.Index(fields=['trip', '-recorded_at'], name='trip_locati_trip_id_82947a_idx'),
        ),
    ]
