# Generated by Django 5.0.6 on 2026-07-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_triprating'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Картой'), ('cash', 'Наличными')], default='card', max_length=8),
        ),
    ]
